<link rel="stylesheet" href="/perch/addons/apps/natures_laboratory/assets/styles.css" />
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.8.0/fullcalendar.min.css" />
<link rel="stylesheet" href="/perch/addons/apps/natures_laboratory/assets/fullcalendar-scheduler/scheduler.css" />

<script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
<script type="text/javascript" src="/perch/addons/apps/natures_laboratory/assets/moment.js"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.8.0/fullcalendar.min.js"></script>
<script src='/perch/addons/apps/natures_laboratory/assets/fullcalendar-scheduler/scheduler.js'></script>

<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>

<script>
$(document).ready(function() {
    $('select').select2({
	    width:'resolve'
    });
});
</script>

<style>
	.select2-container{
		min-width:90px !important;
	}
</style>